"""A 200-function high-school test corpus (PRD success metric 2).

Every entry must render correctly from a bare ``plot(f)`` — no ranges, no
options, no hints. The corpus is curriculum-agnostic (PRD open decision 1):
it is assembled from the function families that appear in *any* secondary
mathematics syllabus, so it stays valid whichever curriculum is chosen later.
"""

from __future__ import annotations

from typing import Final

#: Each entry is source text for ``sympy.sympify`` in the variable ``x``.
CORPUS: Final[tuple[str, ...]] = (
    # --- linear and polynomial (25) --------------------------------------
    "x",
    "2*x + 1",
    "-3*x + 4",
    "x/2 - 3",
    "x**2",
    "x**2 - 4",
    "-x**2 + 2*x + 3",
    "(x - 1)**2",
    "(x + 2)*(x - 3)",
    "x**3",
    "x**3 - 3*x",
    "x**3 - 6*x**2 + 11*x - 6",
    "-x**3 + x",
    "x**4",
    "x**4 - 5*x**2 + 4",
    "x**4 - 2*x**3",
    "x**5 - x",
    "x**5 - 5*x**3 + 4*x",
    "x**6 - x**4",
    "2*x**3 - 9*x**2 + 12*x - 4",
    "(x - 1)*(x - 2)*(x - 3)",
    "(x**2 - 1)**2",
    "x*(x - 1)*(x + 1)",
    "x**2/4 + x - 1",
    "3*x**4 - 4*x**3 - 12*x**2",
    # --- rational functions and poles (30) -------------------------------
    "1/x",
    "1/x**2",
    "1/x**3",
    "1/(x - 1)",
    "1/(x + 3)",
    "1/(x - 2)**2",
    "1/(x**2 - 1)",
    "1/(x**2 + 1)",
    "1/(x**2 - 4)",
    "x/(x - 1)",
    "x/(x**2 + 1)",
    "x/(x**2 - 1)",
    "(x + 1)/(x - 1)",
    "(x**2 - 1)/(x - 1)",
    "(x**2 + 1)/x",
    "(x**2 - 4)/(x - 2)",
    "(2*x + 1)/(x - 3)",
    "x**2/(x - 1)",
    "x**2/(x**2 - 1)",
    "x**3/(x**2 - 1)",
    "1/(x**3 - x)",
    "1/((x - 1)*(x + 2))",
    "(x - 1)/(x**2 - 4)",
    "3/(x**2 + 2)",
    "(x**2 + x)/(x**2 - x)",
    "1/(x**2 + x + 1)",
    "x/(1 - x)",
    "(1 - x)/(1 + x)",
    "1/(1/x)",
    "(x**3 + 1)/(x + 1)",
    # --- radicals and restricted domains (22) ----------------------------
    "sqrt(x)",
    "sqrt(x - 1)",
    "sqrt(x + 4)",
    "sqrt(1 - x)",
    "sqrt(4 - x**2)",
    "sqrt(x**2 - 1)",
    "sqrt(x**2 + 1)",
    "-sqrt(x)",
    "2*sqrt(x) - 1",
    "sqrt(x)/x",
    "x*sqrt(x)",
    "sqrt(sqrt(x))",
    "cbrt(x)",
    "root(x, 3)",
    "x**(1/3)",
    "x**Rational(2, 3)",
    "1/sqrt(x)",
    "1/sqrt(1 - x**2)",
    "sqrt(x**2 - 4)",
    "sqrt(9 - x**2)",
    "sqrt(x*(x - 1))",
    "sqrt(Abs(x))",
    # --- exponential and logarithmic (25) --------------------------------
    "exp(x)",
    "exp(-x)",
    "2**x",
    "3**x",
    "(1/2)**x",
    "exp(x) - 1",
    "exp(-x**2)",
    "x*exp(-x)",
    "x*exp(x)",
    "exp(x)/x",
    "exp(1/x)",
    "log(x)",
    "log(x + 5)",
    "log(x - 1)",
    "log(Abs(x))",
    "log(x**2)",
    "log(x)/x",
    "x*log(x)",
    "log(x)**2",
    "log(1 + exp(x))",
    "1/(1 + exp(-x))",
    "exp(x) - exp(-x)",
    "(exp(x) + exp(-x))/2",
    "log(x, 2)",
    "log(10 - x)",
    # --- trigonometric (35) ----------------------------------------------
    "sin(x)",
    "cos(x)",
    "tan(x)",
    "cot(x)",
    "sec(x)",
    "csc(x)",
    "sin(2*x)",
    "cos(x/2)",
    "2*sin(x) + 1",
    "sin(x) + cos(x)",
    "sin(x)*cos(x)",
    "sin(x)**2",
    "cos(x)**2 - sin(x)**2",
    "sin(x)/x",
    "x*sin(x)",
    "sin(x**2)",
    "sin(1/x)",
    "x*sin(1/x)",
    "tan(x)/x",
    "tan(2*x)",
    "1/sin(x)",
    "1/cos(x)",
    "sin(x) + sin(2*x)/2",
    "sin(x + pi/4)",
    "cos(pi*x)",
    "sin(pi*x)/(pi*x)",
    "exp(-x)*sin(5*x)",
    "sin(x)/(1 + cos(x))",
    "asin(x)",
    "acos(x)",
    "atan(x)",
    "atan(1/x)",
    "sinh(x)",
    "cosh(x)",
    "tanh(x)",
    # --- absolute value, steps, piecewise (25) ---------------------------
    "Abs(x)",
    "Abs(x - 2)",
    "Abs(x) - x",
    "Abs(x**2 - 1)",
    "x*Abs(x)",
    "x/Abs(x)",
    "Abs(x)/x",
    "Abs(sin(x))",
    "sign(x)",
    "sign(sin(x))",
    "floor(x)",
    "ceiling(x)",
    "floor(x/2)",
    "floor(2*x)",
    "x - floor(x)",
    "floor(x) + 1/2",
    "Abs(floor(x))",
    "Piecewise((x, x < 0), (x**2, True))",
    "Piecewise((-1, x < 0), (1, True))",
    "Piecewise((0, x < 0), (x, True))",
    "Piecewise((1/x, x < 0), (x, True))",
    "Max(x, 0)",
    "Min(x, 1)",
    "Max(x, -x)",
    "Abs(Abs(x) - 1)",
    # --- compositions and awkward cases (38) -----------------------------
    "sqrt(Abs(x - 1))",
    "exp(-Abs(x))",
    "sin(exp(x))",
    "exp(sin(x))",
    "log(Abs(sin(x)))",
    "sqrt(sin(x))",
    "Abs(tan(x))",
    "tan(sin(x))",
    "sin(tan(x))",
    "1/(sin(x) + 2)",
    "1/(x*log(x))",
    "x**x",
    "x**(-x)",
    "(1 + 1/x)**x",
    "atan(tan(x))",
    "sqrt(x)/(x - 1)",
    "exp(x)/(1 + exp(x))",
    "(x**2 - 1)/(x**2 + 1)",
    "x/(1 + Abs(x))",
    "Abs(x)**Rational(1, 3)",
    "x**2*sin(1/x)",
    "cos(1/x)",
    "sin(x)*exp(-x**2)",
    "x/(x**2 + 1)**2",
    "1/(1 + x**4)",
    "x**3/(1 + x**2)",
    "(x - 1)/sqrt(x)",
    "log(x**2 + 1)",
    "sqrt(1 + x**2) - x",
    "1 - exp(-x**2)",
    "sin(x)**3",
    "cos(x)**3 - cos(x)",
    "tan(x)**2",
    "sec(x)*tan(x)",
    "x + 1/x",
    "x - 1/x",
    "x**2 + 1/x**2",
    "floor(sin(x)*4)",
)

assert len(CORPUS) == 200, f"the corpus must hold exactly 200 functions, has {len(CORPUS)}"
