"""The tour notebooks must run, and must stay the same notebook.

``examples/mathslate_tour.py`` (marimo) and ``examples/mathslate_tour.ipynb``
(Jupyter) are both generated from ``examples/build_tour.py``. A notebook a
reader opens to check the library is only worth anything if it works, so this
executes the Jupyter twin end to end and asserts the marimo graph is sound.
"""

from __future__ import annotations

import importlib.util
import shutil
import sys
from pathlib import Path
from typing import Any

import pytest

EXAMPLES = Path(__file__).resolve().parents[1] / "examples"
MARIMO_FILE = EXAMPLES / "mathslate_tour.py"
JUPYTER_FILE = EXAMPLES / "mathslate_tour.ipynb"


def _build_module() -> Any:
    spec = importlib.util.spec_from_file_location("build_tour", EXAMPLES / "build_tour.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TestBothFilesExist:
    def test_the_marimo_notebook(self) -> None:
        assert MARIMO_FILE.is_file()

    def test_the_jupyter_notebook(self) -> None:
        assert JUPYTER_FILE.is_file()


class TestTheyAreGeneratedAndCurrent:
    def test_the_marimo_file_matches_its_source(self) -> None:
        """Edit `build_tour.py`, then re-run it. Never edit the output."""
        build = _build_module()
        assert MARIMO_FILE.read_text(encoding="utf-8") == build.build_marimo(), (
            "examples/mathslate_tour.py is stale — run `python examples/build_tour.py`"
        )

    def test_the_generated_file_says_it_is_generated(self) -> None:
        assert MARIMO_FILE.read_text(encoding="utf-8").startswith("# Generated by")

    def test_no_cell_uses_a_name_a_later_cell_defines(self) -> None:
        """marimo would cope; the Jupyter twin runs in file order and would not."""
        build = _build_module()
        build.check_order([build.analyse(cell) for cell in build.CELLS])

    def test_the_tour_is_substantial(self) -> None:
        build = _build_module()
        assert len(build.CELLS) >= 60


class TestTheMarimoGraphIsSound:
    def test_it_loads_with_no_duplicate_or_missing_definitions(self) -> None:
        pytest.importorskip("marimo")
        from marimo._ast.app import InternalApp

        spec = importlib.util.spec_from_file_location("tour", MARIMO_FILE)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        graph = InternalApp(module.app).graph

        duplicates = {name: len(w) for name, w in graph.definitions.items() if len(w) > 1}
        assert duplicates == {}, f"marimo forbids defining a name twice: {duplicates}"
        assert list(graph.cycles) == []

    def test_no_cell_executes_a_star_import(self) -> None:
        """marimo rejects it at parse time — checked on the code, not the prose.

        The tour *discusses* `import *` in a markdown cell, so a substring
        search would fail on the sentence explaining why it is forbidden.
        """
        import ast

        build = _build_module()
        for index, cell in enumerate(build.CELLS):
            for node in ast.walk(ast.parse(build.dedent(cell))):
                if isinstance(node, ast.ImportFrom):
                    names = [alias.name for alias in node.names]
                    assert "*" not in names, f"cell {index} uses a star import"


class TestTheJupyterTwinOpensCleanly:
    def test_it_names_a_kernel(self) -> None:
        """Without a kernelspec, Jupyter asks the reader which kernel to use."""
        import json

        metadata = json.loads(JUPYTER_FILE.read_text(encoding="utf-8"))["metadata"]
        assert metadata["kernelspec"]["name"] == "python3"

    def test_it_carries_no_stored_outputs(self) -> None:
        """Outputs in the file would put megabytes of Plotly into git."""
        import json

        notebook = json.loads(JUPYTER_FILE.read_text(encoding="utf-8"))
        assert not any(cell.get("outputs") for cell in notebook["cells"])

    def test_the_prose_became_real_markdown_cells(self) -> None:
        import json

        notebook = json.loads(JUPYTER_FILE.read_text(encoding="utf-8"))
        kinds = [cell["cell_type"] for cell in notebook["cells"]]
        assert kinds.count("markdown") > 20
        assert kinds.count("code") > 20


class TestItActuallyRuns:
    """The whole point: a reader opens it and every cell works."""

    @pytest.fixture(scope="class")
    def executed(self) -> Any:
        pytest.importorskip("nbclient")
        import nbformat
        from nbclient import NotebookClient

        notebook = nbformat.read(JUPYTER_FILE, as_version=4)
        NotebookClient(
            notebook, timeout=900, kernel_name="python3", allow_errors=True
        ).execute()
        return notebook

    def test_no_cell_raised(self, executed: Any) -> None:
        failures = [
            f"cell {index}: {output['ename']}: {output['evalue'].splitlines()[0]}"
            f"\n    {cell['source'].splitlines()[0][:70]}"
            for index, cell in enumerate(executed.cells)
            for output in cell.get("outputs", [])
            if output.get("output_type") == "error"
        ]
        assert failures == [], "the tour does not run:\n" + "\n".join(failures)

    def test_it_produced_figures(self, executed: Any) -> None:
        rendered = sum(
            1
            for cell in executed.cells
            for output in cell.get("outputs", [])
            if "application/vnd.plotly.v1+json" in output.get("data", {})
        )
        assert rendered >= 15, f"only {rendered} plots rendered"

    def test_it_shows_the_inference_report(self, executed: Any) -> None:
        printed = "".join(
            output.get("text", "")
            for cell in executed.cells
            for output in cell.get("outputs", [])
            if output.get("output_type") == "stream"
        )
        assert "curve | x" in printed
        assert "discontinuit" in printed

    def test_it_reaches_every_headline_feature_in_jupyter(self, executed: Any) -> None:
        printed = "".join(
            output.get("text", "")
            for cell in executed.cells
            for output in cell.get("outputs", [])
            if output.get("output_type") == "stream"
        )
        for evidence in (
            "MathSlate ",          # the version banner
            "inflections",         # analyze()
            "R² = ",          # dataset().fit()
            "eigen pairs",         # linear algebra
            "frames:",             # sliders
            "AmbiguousAxisError",  # the refusals section
        ):
            assert evidence in printed, f"the tour never reached {evidence!r}"


class TestItRunsInMarimoToo:
    """Executing without raising is not the same as drawing something.

    The tour was first shipped verified only against the Jupyter kernel, where
    Plotly's mimebundle renderer is active. In marimo it is not, so every cell
    ran, printed its report, and drew nothing at all — and the suite was green.
    This renders the whole notebook the way marimo does and counts the plots.
    """

    @pytest.fixture(scope="class")
    def rendered(self, tmp_path_factory: pytest.TempPathFactory) -> str:
        pytest.importorskip("marimo")
        import subprocess

        worktree = tmp_path_factory.mktemp("tour")
        source = worktree / MARIMO_FILE.name
        destination = worktree / "rendered.html"
        # Some marimo versions format the notebook during export. Use a copy so
        # a test run can never rewrite the tracked source file.
        shutil.copy2(MARIMO_FILE, source)
        completed = subprocess.run(
            [
                sys.executable, "-m", "marimo", "export", "html",
                str(source), "-o", str(destination),
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            # marimo's progress output is not always valid UTF-8 on a legacy
            # Windows console, and a decode error in the reader thread would
            # surface as an unrelated test warning.
            errors="replace",
            timeout=900,
        )
        if completed.returncode != 0 or not destination.exists():
            pytest.fail(f"marimo could not render the tour:\n{completed.stderr[-2000:]}")
        return _readable(destination.read_text(encoding="utf-8"))

    def test_the_plots_are_actually_drawn(self, rendered: str) -> None:
        drawn = rendered.count("plotly-graph-div")
        assert drawn >= 20, (
            f"marimo rendered only {drawn} plots — the cells ran but produced "
            "no figures, which is what a reader would see as a blank notebook"
        )

    def test_the_animated_plots_keep_their_frames(self, rendered: str) -> None:
        assert rendered.count("addframes") >= 1

    def test_the_tables_are_drawn(self, rendered: str) -> None:
        assert rendered.count("<table") >= 2

    def test_the_analyses_are_drawn(self, rendered: str) -> None:
        """`<details>` is the collapsed panel `Analysis._repr_html_` builds."""
        assert rendered.count("<details") >= 1
        assert "inflections" in rendered


def _readable(exported: str) -> str:
    """Undo marimo's output encoding so the markup can be searched.

    Cell outputs are HTML-escaped into an `<iframe srcdoc>` and then
    JSON-escaped into the page, so a literal `<table>` reaches the file as
    `\\u003Ctable` or `\\u0026lt;table`. Searching for the raw tag finds
    nothing and looks exactly like "nothing rendered" — which is how this
    check first passed for zero plots.
    """
    lowered = exported.lower()
    for escaped, plain in (
        ("\\u0026lt;", "<"),
        ("\\u0026gt;", ">"),
        ("\\u0026quot;", '"'),
        ("\\u003c", "<"),
        ("\\u003e", ">"),
        ("&lt;", "<"),
        ("&gt;", ">"),
    ):
        lowered = lowered.replace(escaped, plain)
    return lowered
