# Generated by examples/build_tour.py — edit the cells there, not here.
import marimo

__generated_with = "0.23.15"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    import numpy as np
    return (mo, np)


@app.cell
def _(mo):
    mo.md(
        r"""
        # MathSlate — a guided tour

        Run every cell. Each one is a claim you can check with your own eyes:
        the graph is right, the inferred settings are stated out loud, and the
        plain Python behind it is one call away.

        This notebook exercises the whole of v1.0 — 2D curves, discontinuities,
        3D, sliders, `analyze()`, tables, data fitting, worksheets and the
        optional AI layer. Nothing here needs a network.
        """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 0. Importing

        marimo rejects `from mathslate import *` before the cell runs — it has
        to know statically which names a cell defines in order to build its
        reactive graph. So the names come in explicitly. Everything else in the
        tour is identical in either notebook.
        """
    )
    return


@app.cell
def _():
    from mathslate import (
        plot, polar, analyze, table, slider, animate, dataset, show_python,
        set_verbose, get_verbose, frontend_report,
        sin, cos, tan, exp, log, sqrt, Abs, floor, sign, pi, Eq, Matrix,
        diff, integrate, limit, solve, solveset, nsolve, simplify, symbols, Rational,
        factor, expand, apart, cancel, together, trigsimp, gcd,
        x, y, z, t, n, k, theta,
    )
    from mathslate.ui import release, release_all
    import mathslate

    print(f"MathSlate {mathslate.__version__} · {frontend_report()}")
    return (Abs, Eq, Matrix, Rational, analyze, animate, apart, cancel, cos, dataset, diff, exp, expand, factor, floor, gcd, get_verbose, integrate, limit, nsolve, plot, polar, release, release_all, set_verbose, simplify, sin, slider, solve, solveset, sqrt, symbols, t, table, tan, together, trigsimp, x, y, z)


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 1. The first graph

        No `symbols`, no `lambdify`, no `linspace`, no `figure`, no `show`.
        `x` already exists, and `sin` is SymPy's own — re-exported, not wrapped.
        """
    )
    return


@app.cell
def _(plot, sin, x):
    first = plot(sin(x)/x)
    first
    return (first,)


@app.cell
def _(mo):
    mo.md(
        r"""
        Read the line it printed. `sin(x)/x` is **undefined at x = 0**, and the
        curve is cut there rather than drawn through a point that does not
        exist. Everything the call decided for you is in that one line.
        """
    )
    return


@app.cell
def _(first):
    print(first.summary())
    for note in first.notes:
        print(" ·", note)
    return (note,)


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 2. The functions that separate a tool from a wrapper

        Look for what is **not** there: no near-vertical line joining the top
        of one branch to the bottom of the next. Those lines are an artefact of
        joining consecutive samples without asking whether the function is
        continuous between them. Most plotters draw them.
        """
    )
    return


@app.cell
def _(plot, tan, x):
    plot(tan(x))
    return


@app.cell
def _(plot, x):
    plot(1/x)
    return


@app.cell
def _(floor, plot, x):
    plot(floor(x))
    return


@app.cell
def _(plot, sqrt, x):
    plot(sqrt(x))
    return


@app.cell
def _(Abs, plot, x):
    plot(x/Abs(x))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        The evidence, rather than the picture: where the line was cut, and
        which stretches of the window the function is actually real on.
        """
    )
    return


@app.cell
def _(Abs, floor, plot, sqrt, tan, x):
    for hard in (tan(x), 1/x, floor(x), sqrt(x), x/Abs(x), 1/(x**2 - 1)):
        cuts = plot(hard, verbose=False).plan.series[0].sample
        print(f"{str(hard):12s} cuts={len(cuts.breakpoints):2d}  real on {cuts.domain_intervals}")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        A steep curve is **not** a discontinuity, and MathSlate tells them
        apart by squeezing the interval and watching whether the jump survives.
        `atan(1000x)` rises almost vertically and is not cut anywhere.
        """
    )
    return


@app.cell
def _(plot, x):
    from sympy import atan

    steep = plot(atan(1000*x), (x, -1, 1), verbose=False)
    print("cuts in atan(1000x):", steep.plan.series[0].sample.breakpoints)
    steep
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 3. Axes that read the expression

        Trigonometry gets π ticks. `exp` does not, because π has nothing to do
        with it. Nobody asked for either.
        """
    )
    return


@app.cell
def _(exp, plot, sin, x):
    print("sin ticks :", list(plot(sin(x), verbose=False).plotly.layout.xaxis.ticktext))
    print("exp ticks :", plot(exp(x), verbose=False).plotly.layout.xaxis.ticktext)
    plot(sin(x))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        A log scale is **suggested, never applied**. A learner reading a
        log-scaled plot without realising it is worse off than one reading an
        awkward linear plot.
        """
    )
    return


@app.cell
def _(exp, note, plot, x):
    growth = plot(exp(x), verbose=False)
    print([note for note in growth.notes if "log scale" in note])
    plot(exp(x), yscale="log")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 4. The one rule

        A **list** means *several things together*. A **tuple** means *one
        vector-valued object*. Same two expressions, different bracket,
        different picture.
        """
    )
    return


@app.cell
def _(cos, plot, sin, x):
    plot([sin(x), cos(x), sin(x) + cos(x)])
    return


@app.cell
def _(cos, plot, sin, t):
    plot((cos(t), sin(t)))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        `r = f(θ)` is written identically to `y = f(x)`, so inference cannot
        decide it in principle — and MathSlate refuses to guess. You say it.
        """
    )
    return


@app.cell
def _(cos, polar, t):
    polar(1 + cos(t))
    return


@app.cell
def _(polar, sin, t):
    polar(sin(3*t))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        Your own numbers work too, as do plain Python functions.
        """
    )
    return


@app.cell
def _(np, plot, x):
    print(plot([2.0, 4.0, 8.0, 16.0, 32.0], verbose=False).plan.kind)
    print(plot(([0.0, 1.0, 2.0, 3.0], [0.0, 1.0, 4.0, 9.0]), verbose=False).plan.kind)
    plot(np.tanh, (x, -5, 5))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 5. `show_python()` — the point of the whole project

        Not pseudocode. Paste it into a file and it runs, and it writes out
        every decision MathSlate made quietly: the real domain in pieces, the
        cuts, the y-window, the π ticks.
        """
    )
    return


@app.cell
def _(plot, tan, x):
    _ = plot(tan(x), verbose=False).show_python()
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        It really runs — here it is, executed in a namespace holding nothing.
        """
    )
    return


@app.cell
def _(plot, sin, x):
    emitted = {}
    exec(plot(sin(x)/x, verbose=False).python(), emitted)
    print(type(emitted["fig"]).__name__, "with", len(emitted["fig"].data[0].x), "points")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 6. Nothing here is a one-way door

        Every result hands you the underlying objects, so you can stop using
        MathSlate at any moment without losing work.
        """
    )
    return


@app.cell
def _(integrate, plot, sin, x):
    hatch = plot(sin(x)/x, verbose=False)
    print("sympy :", hatch.sympy)
    print("numpy :", hatch.numpy[0].shape, hatch.numpy[1].shape)
    print("plotly:", type(hatch.plotly).__name__)
    print("integral of it from 1 to 2 :", integrate(hatch.sympy, (x, 1, 2)).evalf(6))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        And the SymPy re-exports are SymPy — there is nothing to unlearn.
        """
    )
    return


@app.cell
def _(diff, exp, limit, simplify, sin, solve, x):
    print(diff(sin(x)*exp(x), x))
    print(solve(x**2 - 5*x + 6, x))
    print(limit(sin(x)/x, x, 0))
    print(simplify((x**2 - 1)/(x - 1)))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 7. Solving and algebra — SymPy's engine, right here

        MathSlate is a way of *seeing* mathematics, not a computer-algebra
        system: every symbolic computation is delegated to SymPy and the
        functions are re-exported unchanged. So the whole solving and algebra
        toolkit is already imported, and everything below is ordinary SymPy —
        usable, unchanged, in any Python project.
        """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ### Solving

        `solve()` takes an expression (read as `= 0`) or an `Eq`, and returns
        the solutions.
        """
    )
    return


@app.cell
def _(Eq, Rational, sin, solve, x):
    print("expression (= 0) :", solve(x**2 - 5*x + 6, x))
    print("an equation      :", solve(Eq(x**2, 2), x))
    print("a trig equation  :", solve(sin(x) - Rational(1, 2), x))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        A **system** is a list of equations and the unknowns to solve for.
        """
    )
    return


@app.cell
def _(solve, x, y):
    print("two lines meet   :", solve([x + y - 3, x - y - 1], [x, y]))
    print("a circle & a line:", solve([x**2 + y**2 - 1, y - x], [x, y]))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        `solveset()` returns the *whole* solution set — every branch of a
        periodic equation, not just one. `nsolve()` finds a single root
        numerically from a starting guess, for equations with no closed form.
        """
    )
    return


@app.cell
def _(cos, nsolve, sin, solveset, x):
    print("solveset(sin x)  :", solveset(sin(x), x))
    print("nsolve(x - cos x):", nsolve(x - cos(x), x, 0.5))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ### Algebra

        `factor`, `expand` and `gcd` do what they say, over polynomials in any
        number of symbols.
        """
    )
    return


@app.cell
def _(expand, factor, gcd, x):
    print("factor  :", factor(x**3 - x))
    print("expand  :", expand((x + 1)**3))
    print("gcd     :", gcd(x**2 - 1, x**2 - x))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        Rational expressions have their own verbs — `apart` for partial
        fractions, `cancel` and `together` for the two directions of a common
        denominator — and `trigsimp` for the trigonometric identities.
        """
    )
    return


@app.cell
def _(apart, cancel, cos, sin, together, trigsimp, x, y):
    print("apart   :", apart(1/(x**2 - 1)))
    print("cancel  :", cancel((x**2 - 1)/(x - 1)))
    print("together:", together(1/x + 1/y))
    print("trigsimp:", trigsimp(sin(x)**2 + cos(x)**2))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        The point of re-exporting rather than wrapping: whatever SymPy hands
        back is an ordinary expression, so it flows straight into a plot with no
        conversion.
        """
    )
    return


@app.cell
def _(factor, plot, solve, x):
    alg_model = factor(x**3 - 6*x**2 + 11*x - 6)
    print("factored:", alg_model, " roots:", solve(alg_model, x))
    plot(alg_model, (x, 0, 4), verbose=False)
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        There are thousands of SymPy functions and only the common ones are
        re-exported at the top level. The whole library is one attribute away,
        as `mathslate.sympy` — so nothing is ever out of reach.
        """
    )
    return


@app.cell
def _(sin, x, y):
    from mathslate import sympy

    print("linsolve via mathslate.sympy :", sympy.linsolve([x + y - 3, x - y - 1], [x, y]))
    print("a Taylor series              :", sympy.series(sin(x), x, 0, 6))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 8. `analyze()` — properties of the object

        Explicit, never automatic: running property detection on every plot
        would be slow and noisy. It reports what a function **is**, never how a
        result was derived — step-by-step derivation is permanently out of
        scope.
        """
    )
    return


@app.cell
def _(analyze, x):
    cubic = analyze(x**3 - 3*x)
    print(cubic.text())
    return


@app.cell
def _(analyze, x):
    print(analyze(1/x).text())
    return


@app.cell
def _(analyze, sin, x):
    print(analyze(sin(x)).text())
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        Where SymPy can answer exactly it does; where it cannot, the answer is
        labelled approximate rather than quietly presented as exact.
        """
    )
    return


@app.cell
def _(Abs, analyze, x):
    for subject in (x**3 - 3*x, Abs(x), (x**2 - 1)/(x - 1)):
        found = analyze(subject)
        print(f"{str(subject):18s} approximate={found.approximate}")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        `analyze()` is on the result object too, and it renders as a panel.
        """
    )
    return


@app.cell
def _(plot, x):
    plot(x**3 - 3*x, verbose=False).analyze()
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 9. `table()` — the same function as numbers
        """
    )
    return


@app.cell
def _(sin, table, x):
    values = table(sin(x)/x, (x, -1, 1), rows=9)
    print(values.text())
    values
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 10. Interactive mathematics

        You never write a callback. A `Slider` is not a `Symbol`, but it
        answers SymPy's `_sympy_()` hook with one, so `amp*sin(x)` is an
        ordinary expression and everything downstream stays unaware a widget
        was involved.

        Drag the control under the plot.
        """
    )
    return


@app.cell
def _(plot, release_all, sin, slider, x):
    release_all()
    amp = slider(-3, 3, default=1, name="amp")
    waves = plot(amp*sin(x))
    print("frames:", len(waves.plotly.frames), " interactive:", waves.interactive)
    waves
    return (amp,)


@app.cell
def _(mo):
    mo.md(
        r"""
        `animate()` is the same picture with a play button.
        """
    )
    return


@app.cell
def _(amp, animate, sin, x):
    animate(amp*sin(x))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        The slider's symbol is a **parameter**, not an axis — that is the
        binding rule doing its job without being told.
        """
    )
    return


@app.cell
def _(amp, plot, sin, x):
    print("axis symbol:", plot(amp*sin(x), verbose=False).plan.symbol.name)
    print("frame positions:", amp.values()[:5], "...")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ### The one thing to know about sliders

        A slider binds its symbol for the **whole session**, not just the cell.
        That is what makes the line above work without restating anything — and
        it means a slider named after a symbol you also want to plot *over* is
        a collision. MathSlate refuses rather than drawing the frozen point:
        """
    )
    return


@app.cell
def _(cos, plot, sin, slider, t):
    clash = slider(0, 10, default=3, name="t")
    try:
        plot((cos(t), sin(t)))
    except Exception as error:
        print(type(error).__name__)
        print(error)
    return (clash,)


@app.cell
def _(mo):
    mo.md(
        r"""
        Any of the three remedies works. Releasing **that** slider rather than
        every slider matters here: marimo runs independent cells in whatever
        order the graph allows, so a bare `release_all()` could land before the
        cells above that still need `amp`. Naming the slider makes the
        dependency explicit, and the notebook order-proof.
        """
    )
    return


@app.cell
def _(amp, clash, cos, plot, release, sin, t, x):
    release(clash)
    print("after release:", plot((cos(t), sin(t)), verbose=False).plan.kind)
    print("amp is untouched:", plot(amp*sin(x), verbose=False).plan.symbol.name)
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 11. Three dimensions

        One expression with two free symbols is a surface — that is the
        dispatch contract, not a special case. Rotate it with the mouse.
        """
    )
    return


@app.cell
def _(plot, x, y):
    plot(x*y)
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        The same object, flat. This is the other case inference cannot decide.
        """
    )
    return


@app.cell
def _(plot, x, y):
    plot(x*y, kind='contour')
    return


@app.cell
def _(plot, sin, sqrt, x, y):
    plot(sin(sqrt(x**2 + y**2)), (x, -8, 8), (y, -8, 8))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        A surface is ruled with grid lines by default — the sense of curvature a
        bare colour gradient loses. `mesh=False` returns the smooth look. A pole
        is bounded automatically so it cannot wall off the rest; `zlim=` sets the
        window yourself.
        """
    )
    return


@app.cell
def _(plot, x, y):
    plot(x*y, mesh=False, title='mesh=False')
    return


@app.cell
def _(plot, x, y):
    plot(1/(x*y), zlim=(-6, 6), title='a pole, bounded by zlim')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        An equation rather than an expression is an implicit curve.
        """
    )
    return


@app.cell
def _(Eq, plot, x, y):
    plot(Eq(x**2 + y**2, 4))
    return


@app.cell
def _(Eq, plot, x, y):
    plot(Eq(x**2 - y**2, 1))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        Three components sharing one symbol is a space curve; sharing two, a surface.
        """
    )
    return


@app.cell
def _(cos, plot, sin, t):
    plot((cos(t), sin(t), t), (t, 0, 12))
    return


@app.cell
def _(cos, plot, sin, t, z):
    plot((cos(t)*sin(z), sin(t)*sin(z), cos(z)))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 12. Linear algebra

        A matrix draws as what it does to the plane, with its real
        eigenvectors marked.
        """
    )
    return


@app.cell
def _(Matrix, plot):
    transform = plot(Matrix([[2, 1], [1, 3]]))
    print("eigen pairs:", [(round(value, 4), vector.round(4).tolist())
                           for value, vector in transform.plan.eigen])
    transform
    return


@app.cell
def _(Matrix, plot):
    plot(Matrix([[0, -1], [1, 0]]), title='A rotation has no real eigenvector')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 13. `dataset()` — the bridge from symbolic to data

        Everything so far started from an expression. Real work usually starts
        from measurements, and `fit()` is where the two meet: you write the
        model as you would on paper and get **the same expression with its
        parameters filled in**, still a SymPy object.
        """
    )
    return


@app.cell
def _(dataset, symbols):
    a, b, c = symbols("a b c", real=True)
    readings = dataset({
        "x": [0.0, 1.0, 2.0, 3.0, 4.0, 5.0],
        "y": [1.1, 2.9, 5.2, 6.8, 9.1, 11.0],
    })
    print(readings.describe())
    return (a, b, c, readings)


@app.cell
def _(a, b, diff, readings, x):
    straight = readings.fit(a*x + b)
    print(straight.describe())
    print("still SymPy:", straight.expr, "| derivative:", diff(straight.expr, x))
    return (straight,)


@app.cell
def _(plot, straight, x):
    plot([straight.expr], (x, 0, 5), title='the fitted line')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        A model linear **in its parameters** is solved exactly. Anything else
        is refined by damped least squares from several starting points — which
        is what lets a model with a pole in it converge at all.
        """
    )
    return


@app.cell
def _(a, b, c, dataset, exp, np, x):
    curve_x = np.linspace(0.1, 5.0, 60)
    decay = dataset({"x": curve_x, "y": 2.5*np.exp(-0.7*curve_x) + 0.4})
    print(decay.fit(a*exp(b*x) + c).describe())

    poles = dataset({"x": curve_x, "y": 1.0/(curve_x + 0.5) + 0.2})
    print(poles.fit(a/(x + b) + c).describe())
    return (decay,)


@app.cell
def _(mo):
    mo.md(
        r"""
        A fitted model is an ordinary expression, so `analyze()` applies to it.
        """
    )
    return


@app.cell
def _(a, analyze, b, c, decay, exp, x):
    print(analyze(decay.fit(a*exp(b*x) + c).expr).text())
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        Statistics: distributions of a column.
        """
    )
    return


@app.cell
def _(np, plot):
    rng = np.random.default_rng(7)
    sample = rng.normal(loc=10.0, scale=2.0, size=400)
    plot(sample, kind="hist", title="400 draws from a normal")
    return (sample,)


@app.cell
def _(plot, sample):
    plot(sample, kind='box')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 14. Classroom mode — one file you can hand out

        Plots, tables, analyses and prose on one page. Plotly is embedded
        **once** however many figures the page holds, and the result opens with
        no network and nothing installed — including its sliders, which is why
        they are built from frames rather than notebook widgets.
        """
    )
    return


@app.cell
def _(analyze, plot, sin, table, x):
    from mathslate.classroom import worksheet

    handout = worksheet([
        "Where does sin(x)/x go at zero?",
        ("The graph", plot(sin(x)/x, verbose=False)),
        ("The numbers", table(sin(x)/x, (x, -1, 1), rows=7)),
        ("The properties", analyze(sin(x)/x)),
    ], title="Limits", subtitle="A one-page handout")
    handout
    return (handout,)


@app.cell
def _(mo):
    mo.md(
        r"""
        Displaying it shows a card, not the page: a whole HTML document in an
        output cell would restyle the notebook around it. `preview()` puts it
        in a sandboxed frame, and `save()` writes the file.
        """
    )
    return


@app.cell
def _(handout, mo):
    mo.Html(handout.preview(height=420))
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        `handout.save('limits.html')` writes it. Left commented so the tour writes nothing.
        """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 15. The optional AI assistant

        Entirely optional and entirely offline-safe: the core never imports it,
        no provider is bundled, and generated code is shown before it can run.
        The panel guides first-time setup, reports progress and errors, and can
        remember a key in this computer's secure credential manager.
        """
    )
    return


@app.cell
def _():
    from mathslate.ai import assistant, ask

    assistant("plot the tangent over one period")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        The panel is the easiest first step. After setup, the programmatic API
        is equally short:

        ```python
        ask("plot the tangent over one period").run()
        ```

        The example is shown rather than run automatically, so opening the
        tour never sends a request or consumes provider quota.
        """
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 16. What it refuses, and how it says so

        An error message is part of the interface. Each of these is a case
        where guessing would produce something you did not ask for.
        """
    )
    return


@app.cell
def _(a, b, dataset, plot, sin, symbols, x):
    p, q, r_sym = symbols("p q r", real=True)
    attempts = [
        ("three free symbols", lambda: plot(p*q*r_sym)),
        ("a range for a symbol that is not there", lambda: plot(sin(x), (q, -1, 1))),
        ("an unknown option", lambda: plot(sin(x), kind="bar")),
        ("an unplottable object", lambda: plot({"not": "plottable"})),
        ("a model that cannot be separated", lambda: dataset({"x": [1.0, 2.0, 3.0], "y": [2.0, 4.0, 6.0]}).fit(a*b*x)),
        ("fitting a column against itself", lambda: dataset({"v": [1.0, 2.0, 3.0]}).fit(a*x + b)),
    ]
    for label, attempt in attempts:
        try:
            attempt()
            print(f"{label:42s} -> no error")
        except Exception as caught:
            print(f"{label:42s} -> {type(caught).__name__}: {str(caught).splitlines()[0][:70]}")
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 17. Where you are

        Every plot on this page can tell you its plain Python, hand you its
        SymPy expression, and give you its NumPy arrays. That is the whole
        design: the entry barrier of a graphing calculator, and no ceiling.

        - `docs/tutorial.md` — the guided introduction in prose
        - `docs/manual.md` — every option and the exact guarantees
        - `mathslate_prd_0.3.md` — why it is shaped this way
        """
    )
    return


@app.cell
def _(get_verbose, plot, set_verbose, sin, x):
    print("verbosity is switchable:", get_verbose())
    set_verbose(False)
    quiet = plot(sin(x))
    print("silent:", quiet.summary())
    set_verbose(True)
    return


if __name__ == "__main__":
    app.run()
