# Generated by examples/build_tour.py — edit the cells there, not here.
import marimo

__generated_with = "0.23.15"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    import numpy as np
    return (mo,)


@app.cell
def _(mo):
    mo.md(
        r"""
        # MathSlate 3D Plotting Tour

        This notebook is an advanced exploration of 3D plotting with MathSlate.
        It covers surfaces, contours, implicit 3D curves, space curves, and interactive 3D plots.
        """
    )
    return


@app.cell
def _():
    from mathslate import (
        plot, polar, analyze, table, slider, animate, dataset, show_python,
        set_verbose, get_verbose, frontend_report,
        sin, cos, tan, exp, log, sqrt, Abs, floor, sign, pi, Eq, Matrix,
        diff, integrate, limit, solve, simplify, symbols, Rational,
        x, y, z, t, n, k, theta,
    )
    from mathslate.ui import release, release_all
    import mathslate

    print(f"MathSlate {mathslate.__version__} · {frontend_report()}")
    return (animate, cos, exp, pi, plot, release_all, sin, slider, sqrt, symbols, t, x, y)


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 1. Simple Surfaces

        Two free symbols create a 3D surface by default.
        """
    )
    return


@app.cell
def _(plot, x, y):
    plot(x**2 - y**2, (x, -5, 5), (y, -5, 5), title='Saddle')
    return


@app.cell
def _(exp, plot, x, y):
    plot(x * exp(-(x**2 + y**2)), (x, -3, 3), (y, -3, 3), title='Gaussian Peak and Dip')
    return


@app.cell
def _(cos, plot, sin, x, y):
    plot(sin(x) + cos(y), (x, -10, 10), (y, -10, 10), title='Sin-Cos Surface')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        You can explicitly set the range for the two variables.
        """
    )
    return


@app.cell
def _(plot, sin, sqrt, x, y):
    plot(sin(sqrt(x**2 + y**2)), (x, -10, 10), (y, -10, 10), title='Ripples')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 2. Contours

        The same objects can be drawn flat with `kind="contour"`.
        """
    )
    return


@app.cell
def _(plot, x, y):
    plot(x**2 - y**2, kind='contour', title='Saddle (Contour)')
    return


@app.cell
def _(plot, sin, sqrt, x, y):
    plot(sin(sqrt(x**2 + y**2)), (x, -10, 10), (y, -10, 10), kind='contour', title='Ripples (Contour)')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 3. Parametric Surfaces

        A three-component tuple with two shared symbols forms a parametric surface.
        For example, a Torus:
        """
    )
    return


@app.cell
def _(symbols):
    u, v = symbols('u v', real=True)
    return (u, v)


@app.cell
def _(cos, pi, plot, sin, u, v):
    R, r = 3, 1
    plot(
        ((R + r*cos(v))*cos(u), (R + r*cos(v))*sin(u), r*sin(v)),
        (u, 0, 2*pi), (v, 0, 2*pi),
        title='Torus'
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        And a Moebius strip:
        """
    )
    return


@app.cell
def _(cos, pi, plot, sin, u, v):
    plot(
        ((1 + v/2 * cos(u/2)) * cos(u), (1 + v/2 * cos(u/2)) * sin(u), v/2 * sin(u/2)),
        (u, 0, 2*pi), (v, -1, 1),
        title='Moebius Strip'
    )
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 4. Space Curves

        A three-component tuple with one shared symbol forms a 3D space curve.
        """
    )
    return


@app.cell
def _(cos, plot, sin, t):
    plot((sin(t), cos(t), t), (t, 0, 20), title='3D Spiral')
    return


@app.cell
def _(cos, pi, plot, sin, t):
    plot((cos(t)*(3 + cos(5*t)), sin(t)*(3 + cos(5*t)), sin(5*t)), (t, 0, 2*pi), title='Trefoil Knot-like')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## 5. Interactive 3D Surfaces

        We can use sliders to interact with 3D surfaces!
        Let's add a frequency multiplier to the ripple effect.
        """
    )
    return


@app.cell
def _(plot, release_all, sin, slider, sqrt, x, y):
    release_all()
    freq = slider(0.5, 3.0, default=1.0, name='freq')
    plot(sin(freq * sqrt(x**2 + y**2)), (x, -10, 10), (y, -10, 10), title='Interactive Ripples')
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        Let's animate a phase shift on the ripple:
        """
    )
    return


@app.cell
def _(animate, pi, sin, slider, sqrt, x, y):
    phase = slider(0, 2*pi, default=0, name='phase')
    animate(sin(sqrt(x**2 + y**2) - phase), (x, -10, 10), (y, -10, 10), title='Animated Ripples')
    return


if __name__ == "__main__":
    app.run()
